<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="./public/css/estilos.css">
    <title></title>
</head>

<body>
    <div class="alert alert-secondary d-flex">
        <a href="<?= $_ENV['APP_URL'] ?>/peliculas" class="btn btn-dark">Películas</a>&nbsp;&nbsp;
        <a href="<?= $_ENV['APP_URL'] ?>/criticas" class="btn btn-dark">Criticas</a>&nbsp;&nbsp;
    </div>
    <div class="container">
        
    </div>
</body>

</html>